PriceAlert/PriceAlert/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('pricecheck.urls'))
]

PriceAlert/pricecheck/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'pricecheck'

urlpatterns = [
    url(r'^$', views.index, name='index'),  
    url(r'^item/$', views.item, name='item'),
    url(r'^item/alert/$', views.setAlert, name='alert' )
]

PriceAlert/pricecheck/models.py
from django.db import models

# Create your models here.

class Alert(models.Model):
	source = models.CharField(max_length=250)
	item = models.CharField(max_length=100, default="")
	url = models.URLField(default="")
	product_name = models.CharField(max_length=250)
	alert_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
	email_id = models.EmailField(max_length=70,blank=False)

	def __str__(self):
		return self.source + " --- " + self.product_name + " --- " + self.email_id 

PriceAlert/pricecheck/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from . scrap import Fscrap, Ascrap
from . models import Alert

def index(request):
	return render(request, 'pricecheck/index.html')

def item(request):
	baseurl=""
	source = request.POST['location']
	item   = request.POST['q']
	price  = 0

	if (source == "Flipkart"):
		baseurl += "https://www.flipkart.com/search?q="
		baseurl += item.replace(' ','%20')
		price, prod_name = Fscrap(baseurl)

	else :
		baseurl += "https://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords="
		baseurl += item.replace(' ','%20')
		#price, prod_name = Ascrap(baseurl)
		return render(request, 'pricecheck/maintenance.html')
	
	return render(request, 'pricecheck/detail.html', {
		'source' : source,
		'item'   : item,
		'price'  : price,
		'prod_name' : prod_name,
		'baseurl' : baseurl
		})

def setAlert(request):
	if request.method == 'POST':
			finalurl = request.POST['baseurl']
			alert_obj = Alert(source = request.POST['source'], item=request.POST['item'] , url=finalurl, product_name=request.POST['prod_name'], alert_price=request.POST['alert_price'], email_id=request.POST['email_id'])
			alert_obj.save()
	else:
		pass
	return render(request, 'pricecheck/detail.html', { 'message': 'Alert set !!!'})

PriceAlert/pricecheck/templates/pricecheck/alert.html
<form action="{% url '#' %}" method="post"> 
	{% csrf_token %}
	<label> Email at : </label> <input type="text" name="email_id" />
	<label> Price below Rs. : </label> <input type="text" name="alert_price" />
	<input type="submit" value="Submit"/>
</form>

PriceAlert/pricecheck/templates/pricecheck/detail.html
<!-- {% if error_message %}
	<h1> {{ error_message }}</h1>
{% endif %} -->

{% if item %}
	<h2>Your are looking for {{ item }} on {{ source }} </h2>

	<h2>Product name : </h2> <p> {{ prod_name }} </p>
	<h2>Product price : </h2> <p> {{ price }} </p> 

	<h3>Creat an alert on price drop</h3>

	<form action="{% url 'pricecheck:alert' %}" method="post"> 
		{% csrf_token %}
		<input type="hidden" name="item" value= "{{ item }}">
		<input type="hidden" name="prod_name" value= "{{ prod_name }}" >
		<input type="hidden" name="source" value= "{{ source }}">
		<input type="hidden" name="baseurl" value= "{{ baseurl }}">
		<label> <b> Email at : <b></label> <input type="text" name="email_id" />
		<label> <b> When price below Rs. : <b></label> <input type="text" name="alert_price" />
		<input type="submit" value="Submit"/>
	</form>
{% endif %}

{% if message %}
	<b> {{ message}} </b>
{% endif %}

PriceAlert/pricecheck/templates/pricecheck/index.html
{% load static %}

<html>

    <head>
        <title>Price Alert - Get an Amazon/Flipkart price alert!</title>
        <link rel="stylesheet" type="text/css" href="{% static 'pricecheck/style.css' %}" />
    </head>

    <body>
        <div class="info"> </div>
        <div id="content">
            <div class="narrowmain">
                <div id="searchblock">
                    <div id="logo"> Enter Product Name </div>
                    <div id="searchform">
                        <form action="{% url 'pricecheck:item' %}" method="POST">
                            {% csrf_token %}
                            <label > Source Location :</label> 
                            <input type="radio" name="location" id="1" value="Flipkart"/>
                            <label > Flipkart </label>
                            <input type="radio" name="location" id="2" value="Amazon"/>
                            <label > Amazon </label> <br>
                            <div class="searchbox">
                                <input class="searchtext" type="textbox" name="q" size="50" />
                                <button id="submitbtn" class="searchbtn" title="Search" type="submit">Search</button>
                            </div>
                        </form>
                        <div class="sectionhead">Questions or comments? Email me <a href="mailto:ankit.cs.03@gmail.com"> ankit.cs.03@gmail.com </a></div>
                    </div>
                </div>
            </div>
        </div>
    </body>

</html>

PriceAlert/pricecheck/templates/pricecheck/maintenance.html
{% load static %}

<html>
	<head>
		<title>under maintenance</title>
	</head>
	<body>
		<div id="searchform">
			<img src="{% static 'pricecheck/website-under-maintenance.png' %}" alt="Website under maintenance">
		</div>
	<body>
</html>